### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by timbuktu031** [uotw/vidSmooth#3]
nothing happen?

**Comment by uotw** [comment]
Can you be more descriptive?  At what point does nothing happen?  OS?  Sample video that fails?

**Comment by timbuktu031** [comment]
> Can you be more descriptive? At what point does nothing happen? OS? Sample video that fails?

sorry.
My computer Windows 10 and node 12 installed.
I drag mp4 video(150mb) in to vidsmooth and click sample button
but not showing preview .
